version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    ports:
      - '8080:8080'
    networks:
      - mynetwork
    external_links:
      - eureka-server:eureka-server

networks:
  mynetwork:
    external: true