server:
  port: 8080

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: academic-performance-service
          uri: lb://academic-performance-service
          predicates:
            - Path=/academic-performance/**
        - id: faculties-service
          uri: lb://faculties-service
          predicates:
            - Path=/faculties/**
        - id: lectors-service
          uri: lb://lectors-service
          predicates:
            - Path=/lectors/**